# Generated by Django 5.0.1 on 2026-01-28 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Licensed Massage Therapist', max_length=255)),
                ('image', models.ImageField(upload_to='providers/certifications/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'db_table': 'providers_certification',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('thai', 'Thai Massage'), ('reflexology', 'Reflexology'), ('hot_stone', 'Hot Stone Massage'), ('aromatherapy', 'Aromatherapy Massage')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price must be at least $5.00', max_digits=10)),
                ('duration_minutes', models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'providers_service',
                'unique_together': {('provider', 'service_type')},
            },
        ),
    ]
