# Generated by Django 5.0.1 on 2026-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_provider_providers_p_subscri_f71646_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City where services are provided",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Country where services are provided",
                max_length=100,
                null=True,
            ),
        ),
    ]
