# Generated by Django 5.2.10 on 2026-01-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_city_provider_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
