# Generated by Django 5.2.10 on 2026-02-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0007_city_continent_alter_provider_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderAttributeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int", "Integer"),
                            ("bool", "Boolean"),
                        ],
                        default="string",
                        help_text="Controls how providers input this attribute",
                        max_length=10,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "show_on_card",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this attribute should be highlighted on the provider card",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this attribute from provider-facing forms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Attribute Definition",
                "verbose_name_plural": "Provider Attribute Definitions",
                "db_table": "providers_attribute_definition",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="providers.providerattributedefinition",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Attribute Value",
                "verbose_name_plural": "Provider Attribute Values",
                "db_table": "providers_attribute_value",
                "unique_together": {("provider", "definition")},
            },
        ),
    ]
