# Generated by Django 5.2.10 on 2026-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_remove_provider_city_new_remove_provider_country_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, default=''),
        ),
    ]
