# Generated by Django 5.2.10 on 2026-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0011_populate_provider_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
