# Generated by Django 5.2.10 on 2026-02-11 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0015_providerpricing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="providerpricing",
            old_name="apartment_night_2h",
            new_name="apartment_night_whole",
        ),
        migrations.RenameField(
            model_name="providerpricing",
            old_name="outside_night_2h",
            new_name="outside_night_whole",
        ),
    ]
