# Generated by Django 5.2.10 on 2026-02-11 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "providers",
            "0016_rename_apartment_night_2h_providerpricing_apartment_night_whole_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
