# Generated by Django 5.2.10 on 2026-02-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0017_delete_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Preference Group",
                "verbose_name_plural": "Preference Groups",
                "db_table": "providers_preference_group",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="preference_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="General comment displayed at bottom of preferences",
            ),
        ),
        migrations.CreateModel(
            name="PreferenceSubgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="providers.preferencegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preference Subgroup",
                "verbose_name_plural": "Preference Subgroups",
                "db_table": "providers_preference_subgroup",
                "ordering": ["display_order", "name"],
                "unique_together": {("group", "name")},
            },
        ),
        migrations.CreateModel(
            name="PreferenceSubgroupOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="providers.preferencesubgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preference Subgroup Option",
                "verbose_name_plural": "Preference Subgroup Options",
                "db_table": "providers_preference_subgroup_option",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProviderPreferenceCustomOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_custom_options",
                        to="providers.provider",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_options",
                        to="providers.preferencesubgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Preference Custom Option",
                "verbose_name_plural": "Provider Preference Custom Options",
                "db_table": "providers_preference_custom_option",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProviderPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_checked", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="providers.provider",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_preferences",
                        to="providers.preferencesubgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Preference",
                "verbose_name_plural": "Provider Preferences",
                "db_table": "providers_provider_preference",
                "unique_together": {("provider", "subgroup")},
            },
        ),
    ]
