# Generated by Django 5.2.10 on 2026-02-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0018_preferencegroup_provider_preference_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCustomPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_preferences",
                        to="providers.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Custom Preference",
                "verbose_name_plural": "Provider Custom Preferences",
                "db_table": "providers_custom_preference",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
