# Generated by Django 5.2.10 on 2026-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0019_providercustompreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="map_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Cached latitude for map display (geocoded from district/city)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="map_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Cached longitude for map display (geocoded from district/city)",
                max_digits=9,
                null=True,
            ),
        ),
    ]
