# Generated by Django 5.2.10 on 2026-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0020_provider_map_latitude_provider_map_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="profile_video",
            field=models.FileField(
                blank=True, null=True, upload_to="providers/videos/"
            ),
        ),
    ]
