# Generated by Django 5.2.10 on 2026-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0021_provider_profile_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='bank_account_encrypted',
        ),
        migrations.AlterField(
            model_name='provider',
            name='subscription_payment_method',
            field=models.CharField(blank=True, choices=[('crypto', 'Cryptocurrency')], max_length=20, null=True),
        ),
    ]
