# Generated by Django 5.2.12 on 2026-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0022_remove_bank_account_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='crypto_address',
            field=models.CharField(blank=True, default='', help_text='Bitcoin/Ethereum address', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='subscription_payment_method',
            field=models.CharField(blank=True, choices=[('crypto', 'Cryptocurrency')], default='', max_length=20),
        ),
    ]
