# Generated by Django 5.0.1 on 2026-01-28 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_certification_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=29.99, help_text='Subscription cost in USD', max_digits=10)),
                ('payment_method', models.CharField(choices=[('crypto_bitcoin', 'Bitcoin'), ('crypto_ethereum', 'Ethereum'), ('crypto_usdc', 'USDC'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Transaction hash for crypto, transaction ID for bank', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes', null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'db_table': 'payments_subscription_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
