# Generated by Django 5.0.1 on 2026-01-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
