# Generated by Django 5.2.10 on 2026-03-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionpayment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='nowpayments_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='NOWPayments internal payment ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='pay_address',
            field=models.CharField(blank=True, help_text='Crypto address the provider must send funds to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exact crypto amount the provider must send', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='pay_currency',
            field=models.CharField(blank=True, help_text='Cryptocurrency code (e.g. btc, eth)', max_length=20, null=True),
        ),
    ]
