# Generated by Django 5.2.12 on 2026-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscriptionpayment_nowpayments_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('crypto_bitcoin', 'Bitcoin'), ('crypto_ethereum', 'Ethereum'), ('crypto_usdc', 'USDC')], max_length=20),
        ),
    ]
