# Generated by Django 5.2.12 on 2026-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_subscriptionpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='pay_currency',
            field=models.CharField(blank=True, help_text='NOWPayments currency code (e.g. usdterc20, usdttrc20)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('usdterc20', 'Tether USD (ERC-20)'), ('usdttrc20', 'Tether USD (TRC-20)')], max_length=50),
        ),
    ]
