# Generated by Django 5.2.12 on 2026-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscriptionpayment_pay_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='actually_paid',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Actual crypto amount received (from NOWPayments IPN)', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Paid')], default='pending', max_length=20),
        ),
    ]
