# Generated by Django 5.2.12 on 2026-05-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscriptionpayment_actually_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='pay_currency',
            field=models.CharField(blank=True, help_text='NOWPayments currency code (e.g. usdtmatic)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('usdtmatic', 'Tether USD (Polygon)')], max_length=50),
        ),
    ]
