# Generated by Django 5.2.12 on 2026-05-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_subscriptionpayment_pay_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('usdtmatic', 'Tether USD (Polygon)'), ('usdtbsc', 'Tether USD (BSC)')], max_length=50),
        ),
    ]
