# Generated by Django 5.2.12 on 2026-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_subscriptionpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice_url',
            field=models.URLField(blank=True, help_text='NOWPayments hosted invoice URL (encodes address + amount + network; used as QR code content)', max_length=500, null=True),
        ),
    ]
