# Generated by Django 5.2.12 on 2026-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_subscriptionpayment_invoice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='invoice_url',
            field=models.URLField(blank=True, default='', help_text='NOWPayments hosted invoice URL (encodes address + amount + network; used as QR code content)', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='nowpayments_payment_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='NOWPayments internal payment ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='pay_address',
            field=models.CharField(blank=True, default='', help_text='Crypto address the provider must send funds to', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='pay_currency',
            field=models.CharField(blank=True, default='', help_text='NOWPayments currency code (e.g. usdtmatic)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='Transaction hash for crypto, transaction ID for bank', max_length=255),
        ),
    ]
